name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get github.com/vkuznet/x509proxy
        go get github.com/prometheus/client_golang/prometheus
        go get github.com/prometheus/common
        go get github.com/shirou/gopsutil/process
        go get github.com/shirou/gopsutil/mem
        go get github.com/shirou/gopsutil/load
        go get github.com/shirou/gopsutil/cpu

    - name: Build
      run: |
        go build cmsweb-ping.go
        go build cpy_exporter.go
        go build das2go_exporter.go
        go build eos_exporter.go
        go build http_exporter.go
        go build process_exporter.go
        go build reqmgr_exporter.go
        go build wmcore_exporter.go
        mkdir cmsweb-exporters
        mv cmsweb-ping cpy_exporter das2go_exporter eos_exporter http_exporter process_exporter \
        reqmgr_exporter wmcore_exporter cmsweb-exporters
        tar cfz cmsweb-exporters.tar.gz cmsweb-exporters


    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binary
      id: upload-auth-proxy-server
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cmsweb-exporters.tar.gz
        asset_name: cmsweb-exporters.tar.gz
        asset_content_type: application/octet-stream



    - name: Build image
      run: |
        curl -ksLO https://raw.githubusercontent.com/dmwm/CMSKubernetes/master/docker/exporters/Dockerfile
        docker build . --tag docker.pkg.github.com/dmwm/cmsweb-exporters/cmsweb-exporters
        docker tag docker.pkg.github.com/dmwm/cmsweb-exporters/cmsweb-exporters registry.cern.ch/cmsweb/exporters

    - name: Login to registry.cern.ch
      uses: docker/login-action@v1.6.0
      with:
        registry: registry.cern.ch
        username: ${{ secrets.CERN_LOGIN }}
        password: ${{ secrets.CERN_TOKEN }}

    - name: Publish image to registry.cern.ch
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.CERN_LOGIN }}
        password: ${{ secrets.CERN_TOKEN }}
        registry: registry.cern.ch
        repository: cmsweb/exporters
        tag_with_ref: true

